'use client'
import React from 'react';
import DataTable from '@/Components/SuperAdmin/DataTable';

const invoicesData = [
    { id: 'INV-001', company: 'Tech Solutions Inc.', customer: 'Acme Corp', amount: '$1,200.00', date: '2023-10-01', status: 'Paid' },
    { id: 'INV-002', company: 'Global Trading Co.', customer: 'Beta Ltd', amount: '$3,450.00', date: '2023-10-02', status: 'Pending' },
    { id: 'INV-003', company: 'Small Biz LLC', customer: 'Gamma Inc', amount: '$150.00', date: '2023-10-03', status: 'Overdue' },
    { id: 'INV-004', company: 'Creative Agency', customer: 'Delta Co', amount: '$2,800.00', date: '2023-10-04', status: 'Paid' },
    { id: 'INV-005', company: 'Tech Solutions Inc.', customer: 'Epsilon LLC', amount: '$900.00', date: '2023-10-05', status: 'Paid' },
];

const columns = [
    { header: 'Invoice ID', accessor: 'id' },
    { header: 'Company', accessor: 'company' },
    { header: 'Customer', accessor: 'customer' },
    { header: 'Amount', accessor: 'amount' },
    { header: 'Date', accessor: 'date' },
    {
        header: 'Status',
        accessor: 'status',
        render: (row: any) => (
            <span className={`px-2 py-1 rounded-full text-xs font-medium ${row.status === 'Paid' ? 'bg-green-100 text-green-700' :
                    row.status === 'Pending' ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700'
                }`}>
                {row.status}
            </span>
        )
    },
];

export default function InvoicesPage() {
    return (
        <div className="space-y-6">
            <div>
                <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Invoices</h1>
                <p className="text-gray-500 dark:text-gray-400">View all invoices generated by companies</p>
            </div>

            <DataTable
                title="Recent Invoices"
                columns={columns}
                data={invoicesData}
            />
        </div>
    );
}
